### ISSUE TITLE
Quick Question?

### ISSUE THREAD

**Issue by Syriamanal** [xxFlare/LoadBalancer#10]
Are You Guys FlareHub?
If so you guys might know me im Shadi Nachat on twitter the on defending FlareHub from Williamtdr

if he says any thing tell him i said he cant use Walls or Spleef since i was the first to ever make it if he says u cant use Hg since he made it first

**Comment by LDX-MCPE** [comment]
@xxFlare is the owner of FlareHub, yes, but he doesn't need support from a known scammer and ban evader.

**Comment by AndreyNazarchuk** [comment]
@LDX-MCPE Lol, nice one! :dart:

**Comment by xxFlare** [comment]
@Syriamanal 

Please only open issues when there is an actual issue. This is not a chat-thread.

What happened was, people kept making tweets saying "lbsg suks FlareHub better" and caused anger between lbsg staff.

Though, most of the other things william talked about have been resolved privately.

**Comment by Syriamanal** [comment]
@LDX-MCPE Scammer? i'm not a scammer i have never ever ever scammed any one nor have i dealt with some one online, And i don't ban envade

**Comment by LDX-MCPE** [comment]
*defends his character*

*threatens to DDoS me*

**Comment by Syriamanal** [comment]
@LDX-MCPE when did i say ill ddos you u autistic retard? i said DOX big diff

**Comment by xxFlare** [comment]
Dox can mean ddos too.

And if you look at @LDX-MCPE work, I think you should think twice before calling him a "autistic retard" because he accomplished more things then anything you have done. Thus he has been contributing since this MCPE community started making PocketMine better. Please show some respect.
