### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [xxFlare/LoadBalancer#9]
So... this is how it ends? you guys finish the plugin but don't upload it? wow :'(

**Comment by LDX-MCPE** [comment]
I don't think it's finished yet.

**Comment by AndreyNazarchuk** [comment]
I know its not, but there has not been any work in a while, and my cmmit
was not merged, and knowing ember, he already finished and deployed it.

**Comment by AndreyNazarchuk** [comment]
TOLD YOU!
^^^When you don't mean to hit capslock but you do and realize that you did want to^^^

**Comment by xxFlare** [comment]
As @LDX-MCPE  said, the plugin is not finished yet.

I need to test with my android device since it can only run 0.11 betas.

The code hasn't been tested at all, therefore I can't release it on forums yet because that would be silly for me to do.

**Comment by AndreyNazarchuk** [comment]
OK, cool (first thing you have said to me in MONTHS even if it was not
direct, I see your grammar has improved!)
